In [1]:
import numpy as np

In [3]:
a = np.array([0,1,2])
a

array([0, 1, 2])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [13]:
print(a)

[100   1   2]


In [6]:
a

array([0, 1, 2])

In [14]:
a[0]=1;
type(a)

numpy.ndarray

In [15]:
import pandas as pd

print(pd.__version__)

2.1.1


In [34]:
data ={
    'no':[1,2,3],
    'nama':['agus','indah','ita'],
    'kelamin':['L','P','P']
}

df = pd.DataFrame(data,columns=['no','nama','kelamin'])
df

df['alamat'] = ['trayu','kendal','semarang']
df

no   nama kelamin    alamat
0   1   agus       L     trayu
1   2  indah       P    kendal
2   3    ita       P  semarang

In [53]:
df['alamat']

0       trayu
1      kendal
2    semarang
Name: alamat, dtype: object

In [41]:
df.dtypes

no          int64
nama       object
kelamin    object
alamat     object
dtype: object

In [52]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [54]:
df

no   nama kelamin    alamat
0   1   agus       L     trayu
1   2  indah       P    kendal
2   3    ita       P  semarang

In [59]:
df[['alamat','nama']]

alamat   nama
0     trayu   agus
1    kendal  indah
2  semarang    ita

In [64]:
df.loc[1:2,['no','nama']]

no   nama
1   2  indah
2   3    ita

In [65]:
df

no   nama kelamin    alamat
0   1   agus       L     trayu
1   2  indah       P    kendal
2   3    ita       P  semarang

In [71]:
aa = df[df['no']<3]
aa

no   nama kelamin  alamat
0   1   agus       L   trayu
1   2  indah       P  kendal

In [77]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Inisialisasi stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Teks yang akan distem
text = "perkuliahan praktikum tidak dilakukan"

# Melakukan stemming
stemmed_text = stemmer.stem(text)

# Cetak teks setelah stemming
print(stemmed_text)

kuliah praktikum tidak laku
